# Generated by Django 4.1.7 on 2023-02-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('sabor', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
